### ISSUE TITLE
Add comments in Java code

### ISSUE THREAD

**Issue by petrdvorak** [lime-company/lime-security-powerauth-webauth#10]
Please add JavaDoc comments on top of every class and method, keep the code documented before you push it in the repository.

We are not in such hurry we should keep our code undocumented... :-)

**Comment by romanstrobl** [comment]
Indeed, I will work on comments for existing code.

**Comment by romanstrobl** [comment]
I wrote JavaDoc and documentation for the JavaScript classes and functions, I think we can close the issue for now. I will keep updating the documentation as I add new code.
