### ISSUE TITLE
Remove 'HttpStatus' from model object

### ISSUE THREAD

**Issue by petrdvorak** [lime-company/lime-security-powerauth-webauth#11]
Model objects (especially those used by third parties) should not know anything about HTTP protocol and they should not contain attributes for HTTP status. HTTP status should be handled on the networking level only.

**Comment by romanstrobl** [comment]
Yes, I will redesign the model based on Next Step server model and remove the HTTP status field.

**Comment by romanstrobl** [comment]
Fixed by migration to updated model
