### ISSUE TITLE
Remove 'WebSocketJsonMessage' from resolving services

### ISSUE THREAD

**Issue by petrdvorak** [lime-company/lime-security-powerauth-webauth#12]
We should keep the "separation of concerns" better in the code. The class that is responsible for resolving Next Step Server messages, for example, should not be aware of the fact we use WebSockets for communication with thin clients.

**Comment by romanstrobl** [comment]
The class NextStepService.java doesn't contain any reference to WebSockets - this is the class responsible for resolving Next Server messages.

I do use WebSockets in the NextMessageResolutionService which is used to map a response from the Next step server to a concrete message to show to the user. So, you want to add an extra layer here?

**Comment by petrdvorak** [comment]
WebSockets are removed in favor of AJAX calls.
