### ISSUE TITLE
Implement web application localization

### ISSUE THREAD

**Issue by petrdvorak** [lime-company/lime-security-powerauth-webauth#13]
We need to figure out how to localize the web application. There are multiple tasks / problem dimensions that need to be taken care of:

- Locale auto-detection.
- Manual locale switching.
- Dynamic text localization (customizable texts).
- Thymeleaf template localization.
- React.js components localization.

**Comment by romanstrobl** [comment]
Changes are implemented in branch issue-13: 
https://github.com/lime-company/lime-security-powerauth-webauth/compare/Issue-13?expand=1

**Comment by romanstrobl** [comment]
Changes were merged to master in commit c45f804808dafa05089fbb4979550f06e69f5e55.
Closing issue.
