### ISSUE TITLE
Implement persistent storage of OAuth 2 clients in DB 

### ISSUE THREAD

**Issue by petrdvorak** [lime-company/lime-security-powerauth-webauth#15]
Currently, we have `OAuth2AuthorizationServerConfiguration` with in-memory database of one client ("foo"/"bar"). We should implement DB storage for this.

**Comment by romanstrobl** [comment]
DDL script for this change:

create table oauth_client_details (
  client_id VARCHAR(256) PRIMARY KEY,
  resource_ids VARCHAR(256),
  client_secret VARCHAR(256),
  scope VARCHAR(256),
  authorized_grant_types VARCHAR(256),
  web_server_redirect_uri VARCHAR(256),
  authorities VARCHAR(256),
  access_token_validity INTEGER,
  refresh_token_validity INTEGER,
  additional_information VARCHAR(4096),
  autoapprove VARCHAR(256)
);

create table oauth_client_token (
  token_id VARCHAR(256),
  token LONG VARBINARY,
  authentication_id VARCHAR(256) PRIMARY KEY,
  user_name VARCHAR(256),
  client_id VARCHAR(256)
);


create table oauth_access_token (
  token_id VARCHAR(256),
  token LONG VARBINARY,
  authentication_id VARCHAR(256) PRIMARY KEY,
  user_name VARCHAR(256),
  client_id VARCHAR(256),
  authentication LONG VARBINARY,
  refresh_token VARCHAR(256)
);

create table oauth_refresh_token (
  token_id VARCHAR(256),
  token LONG VARBINARY,
  authentication LONG VARBINARY
);

create table oauth_code (
  code VARCHAR(255), 
  authentication LONG VARBINARY
);

insert into oauth_client_details (client_id, client_secret, scope, authorized_grant_types, additional_information, autoapprove) values ('democlient', 'changeme', 'profile', 'authorization_code', '{}', 'true');
