### ISSUE TITLE
Implement dynamic step resolution logic in Next Step server

### ISSUE THREAD

**Issue by romanstrobl** [lime-company/lime-security-powerauth-webauth#19]
Currently all logic is hardcoded in the Next Step server. We need to implement dynamic step resolution for different operation types (user authentication, payment authorization, etc. - in future additional operation types can be added). Responses for different operations in different states should be defined in the database, multiple steps can be returned in a single response with priorities also taken from the database. Furthermore the state of each operation will be kept in the database. We will also store history of responses for each operation and this information can be leveraged when generating the Next Step response.

In the first implementation we will support following operation types:
- user authentication (login)
- payment authorization

Following methods will be implemented:
1. init operation - POST method is used to initiate a new operation. During this phase a unique operation ID is generated. The response is generated using steps defined in the database based on their priorities - we will use two steps: a) user_id_assign, b) username_password_auth.
2. update operation - PUT method is used to update an existing operation. The operation is retrieved from the database based on operationId. The logic for generating a response will differ based on the operation type (login and payment authorization actions have different requirements). During next step resolution we should avoid hardcoding any logic in code, step resolution logic definition should be taken from the database instead.
3. get operation status - it is also possible to retreive status of an existing operation. POST HTTP method is used to avoid exposing sensitive information in the URL. The action will not only return current operation state, it will also return history for this operation (e.g. including previous result of authentication).

Implementation notes:
- use Spring Repository for working with DB
- DDL to be made available in some file in git in consolidated form (add oauth table DDL as well)

Additional notes related to this code change:
- remove all description properties, they are not needed
- operationData can contain arbitrary data - we will not assume understanding this data
- don't forget to handle the operation confirmation (e.g. confirm payment action)
- handle cancellations triggered by the user
- implement error handling

Additional requirements (may be implemented later):
- handle expiration of operations
- support for user preferences - preferences will be used to filter steps in responses based on available services for the user (we need to perform a query to know what to filter, services may be activated/deactivated at any time)
- support for offline tokens
- fallback in case of a failure to a step with a lower priority

**Comment by romanstrobl** [comment]
Basic functionality described in this request is implemented in issue-22. We'll need to make some decisions about implementation of "additional requirements":
* expiration of operations - I suggest that during each operation request we will check expiration time of the previous operation step in ns_operation_history. In case the new request arrived after timeout, current step will return FAILED auth_step_result.
* support for user preference - I suggest we add another column into ns_step_definition (e.g. 'prerequisites') which will contain comma separated names of prerequisite steps. We can add. e.g. CHECK_USER_PREFERENCES prerequisite and the filtering of steps will trigger actual check of user preferences. In case this check fails, the step definition will be filtered out. The reason for the new column is to avoid hardcoding any NS functionality.
* Fallback in case of failure - I suggest we detect previously failed steps and in case there are multiple steps available with different priorities, fall back to the step which is next by the priority. We can also check for earlier failures in the history to filter out steps which failed before. In case there is only 1 last step priority left, we will return this step - filtering it out would lead to void step definition (we can consider whether it would be better to return to priority 1 in case all step priorities previously failed).
* Support for offline tokens - I suggest we handle this separately, I also will need more information to implement it.

**Comment by petrdvorak** [comment]
I will keep this issue opened for now - I will close it after we open related enhancements...

**Comment by romanstrobl** [comment]
All related enhancements have been filed, see #25, #28, #29, #30, #32 and #33. Closing issue.
