### ISSUE TITLE
Create NextStep method to obtain all pending operations for given "userId"

### ISSUE THREAD

**Issue by petrdvorak** [lime-company/lime-security-powerauth-webauth#20]
In order to implement the mobile token endpoints, we need to have a way to obtain all pending operations for given user. Therefore, we need a separate endpoint `POST /user/operation/list` on the Next Step server.

The request object should have one mandatory parameter - `userId` - and optional parameter `authMethod` to return only the operations that can be authorized using a provided `authMethod` (if not specified, all pending operations should be returned).

The response should return a collection (list) of objects that are following the structure of `GetOperationDetailResponse` object...

**Comment by romanstrobl** [comment]
Ok, I will implement it.

**Comment by romanstrobl** [comment]
Implemented in branch issue-20. See pull request issue-23.
