### ISSUE TITLE
Null operationId in show operation detail action

### ISSUE THREAD

**Issue by romanstrobl** [lime-company/lime-security-powerauth-webauth#21]
The PUT call on /operation contains null operationId in the request to the Next Step server REST API. This happens only during the show operation detail action, during login the operationId is not null. See screenshot:

![null_operation_id](https://cloud.githubusercontent.com/assets/26658588/26827800/183ef0ca-4abf-11e7-949e-fd30fb097ab6.png)

**Comment by romanstrobl** [comment]
It seems that the null value is returned in method updateAuthenticationWithUserId() of AuthenticationManagementService class - see lines 89-90:

https://github.com/lime-company/lime-security-powerauth-webauth/blob/6033b8006e48c071f3a145ad85df63bcbabaa778/powerauth-webauth-authentication/src/main/java/io/getlime/security/powerauth/lib/webauth/authentication/service/AuthenticationManagementService.java

**Comment by petrdvorak** [comment]
Did you use a correct session ID (`Cookie` header) for the calls? The code seems correct to me - in case of operation review, the user ID is obtained from the session (in case user is logged in, otherwise this must be an incorrect sequence)...

**Comment by romanstrobl** [comment]
I can reproduce this issue easily during any session with SHOW_OPERATION_DETAIL auth method.

Here are steps to reproduce:
1. Run 'mvn package' on powerauth-webauth-parent project.
2. Deploy jars to Tomcat.
3. Open web browser and go to: http://localhost:8080/powerauth-webauth-client
4. Start Wireshark, monitor http protocol on loopback interface.
5. Click 'Log in' in the browser.
6. Sign in successfully. Note that operationId is correct in PUT request to NS server:
<img width="1072" alt="screen shot 2017-06-06 at 22 07 52" src="https://user-images.githubusercontent.com/26658588/26849501-bb4e6c38-4b04-11e7-8848-af560283873a.png">
7. Confirm the operation. Check the operationId in latest PUT request to NS server:
<img width="1072" alt="screen shot 2017-06-06 at 22 09 49" src="https://user-images.githubusercontent.com/26658588/26849540-eb254b98-4b04-11e7-8b9c-ee1a3daa5b5a.png">

**Comment by romanstrobl** [comment]
Issue is fixed in branch issue-19

**Comment by petrdvorak** [comment]
... I see it... this was dumb... sorry.
