### ISSUE TITLE
Operation ordering in next step server

### ISSUE THREAD

**Issue by petrdvorak** [lime-company/lime-security-powerauth-webauth#24]
Currently, operations returned from Next Step are returned in random order (as DB provides them).

We should probably sort the operations from the one that expires the first, so that client apps do not have to do the sorting... User should be primarily notified of the operation he submitted first (and will expire first).

Anyway - in most cases, there will only be one operation.

**Comment by romanstrobl** [comment]
Agreed, I will work on it.

**Comment by romanstrobl** [comment]
Implemented in branch issue-25, included in pull request #31 (it is closely related to expiration handling).

**Comment by romanstrobl** [comment]
Pull request was merged to master, closing issue.
