### ISSUE TITLE
Expiration handling in Next Step server

### ISSUE THREAD

**Issue by petrdvorak** [lime-company/lime-security-powerauth-webauth#25]
Currently, we do not handle expiration in any way. We should first specify exact logics for expiration handling and then implement it.

**Comment by romanstrobl** [comment]
Here is the description of expiration logic we figured out so far for the Next Step server:
* Operations will have expiration timestamp similar to operation history (and they will have a create  timestamp as well).
* Expiration timestamp will be updated on each PUT action to match the timestamp of newly added step into the operation history.
* On each PUT action for an operation, expiration timestamp will be checked. In case expiration time is exceeded, the operation will fail.
* Expiration time should be configurable via application.properties.

As part of this change we should implement UI for handling failed operations, it will be useful for testing operation expiration.

**Comment by romanstrobl** [comment]
Implemented in branch issue-25, pull request #31

**Comment by romanstrobl** [comment]
Pull request was merged to master, closing issue.
