### ISSUE TITLE
Add displayable attributes to auth methods

### ISSUE THREAD

**Issue by petrdvorak** [lime-company/lime-security-powerauth-webauth#43]
We should add attributes to auth methods in database that would allow us to display the auth methods in UI. Namely, we should add:

- `has_user_interface` attribute - so that we know if we can display some UI in web app
- `key_display_name` - so that we can show description on tab (for example, "app.mtoken" => L10N "Mobile Token")

**Comment by romanstrobl** [comment]
Implemented, see #71.
