### ISSUE TITLE
Add support for rejecting operations [Next Step]

### ISSUE THREAD

**Issue by petrdvorak** [lime-company/lime-security-powerauth-webauth#52]
Currently, we only have a request for accepting the operation. We should also have 1FA-authorized endpoint for rejecting the operation. We should also ask user for the rejection reason:

- do not want to tell
- operation data is wrong
- I didn't enter the operation
- expired / canceled

**Comment by romanstrobl** [comment]
Implemented in issue-51 (branch contains both issue-51 and issue-52 implementation).
