### ISSUE TITLE
Compilation error in class MobileTokenApiExceptionResolver

### ISSUE THREAD

**Issue by romanstrobl** [lime-company/lime-security-powerauth-webauth#77]
I am getting a compilation error in class MobileTokenApiExceptionResolver:

https://github.com/lime-company/lime-security-powerauth-webauth/blob/master/powerauth-webauth-authentication-mtoken/src/main/java/io/getlime/security/powerauth/lib/webauth/authentication/mtoken/exception/MobileTokenApiExceptionResolver.java

Method Error.genericError() is missing, see Error class:
https://github.com/lime-company/lime-java-core/blob/master/rest-model-base/src/main/java/io/getlime/core/rest/model/base/entity/Error.java

**Comment by petrdvorak** [comment]
... caused by using old core Java classes - last commit uses 1.0.2 that corrects the error with default constructor, instead of static method.
