### ISSUE TITLE
No suitable constructor found for ObjectResponse

### ISSUE THREAD

**Issue by romanstrobl** [lime-company/lime-security-powerauth-webauth#78]
Try to login with empty credentials in Web Flow application. The following error is shown:

Can not construct instance of io.getlime.security.powerauth.lib.credentials.model.entity.CredentialStoreError: no suitable constructor found, can not deserialize from Object value (missing default constructor or creator, or perhaps need to add/enable type information?) at [Source: {"status":"ERROR","responseObject":{"code":"INPUT_INVALID","message":"validation.error","validationErrors":["login.username.empty","login.password.empty"]}}; line: 1, column: 37] (through reference chain: io.getlime.core.rest.model.base.response.ObjectResponse["responseObject"])

![image](https://user-images.githubusercontent.com/26658588/28790363-14176988-7629-11e7-9006-7c97ed28c294.png)

**Comment by petrdvorak** [comment]
... caused by using old core Java classes - last commit uses 1.0.2 that corrects the error with missing default constructor.
