### ISSUE TITLE
Remove 'toJson' method from model classes

### ISSUE THREAD

**Issue by petrdvorak** [lime-company/lime-security-powerauth-webauth#8]
Model class modules should keep information about classes, not about the way they are represented in a transport level. As a result, we should:

- remove 'toJson' method from classes in `powerauth-credential-server-model`
- remove model dependency on `spring-web` in `pom.xml`
- remove `@JsonProperty` annotations

Object to JSON serialization should be performed in the connector application, in a manner that choses the implementor.

**Comment by romanstrobl** [comment]
Agreed

**Comment by romanstrobl** [comment]
Issue is fixed
